#!/bin/sh
"C:\Users\Q-CTRL\.conda\envs\control\python.exe" -m gitauthor

branch="$(git rev-parse --abbrev-ref HEAD)" 

if [ "$branch" = "master" ]; then 
  echo "You can't commit directly to master branch" 
  exit 1 
fi
